export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const MARK_USER_POSITIVE_SUCCESS = 'MARK_USER_POSITIVE_SUCCESS';
export const MARK_USER_POSITIVE_FAILURE = 'MARK_USER_POSITIVE_FAILURE';
export const MARK_USER_RECOVERED_SUCCESS = 'MARK_USER_POSITIVE_SUCCESS';
export const MARK_USER_RECOVERED_FAILURE = 'MARK_USER_POSITIVE_FAILURE';